from flask import Flask, render_template, request
from Savoir import Savoir
from creds import *

# RPC call wrappers simplified and abstracted through savoir
# which are located in creds.py


app = Flask(__name__)
@app.route('/')
def hello():
    return render_template('index.html',
    abcGBP = str(abcassets[0]['issueqty']), # These were generated by a dict script
    abcUSD = str(abcassets[1]['issueqty']),
    abcCAD = str(abcassets[2]['issueqty']),
    abcBTC = str(abcassets[3]['issueqty']),
    abcETH = str(abcassets[4]['issueqty']),

    corp1GBP = str(corp1assets[0]['issueqty']),
    corp1USD = str(corp1assets[1]['issueqty']),
    corp1CAD = str(corp1assets[2]['issueqty']),
    corp1BTC = str(corp1assets[3]['issueqty']),
    corp1ETH = str(corp1assets[4]['issueqty']),
    
    corp2GBP = str(corp2assets[0]['issueqty']),
    corp2USD = str(corp2assets[1]['issueqty']),
    corp2CAD = str(corp2assets[2]['issueqty']),
    corp2BTC = str(corp2assets[3]['issueqty']),
    corp2ETH = str(corp2assets[4]['issueqty']),
    
    corp3GBP = str(corp3assets[0]['issueqty']),
    corp3USD = str(corp3assets[1]['issueqty']),
    corp3CAD = str(corp3assets[2]['issueqty']),
    corp3BTC = str(corp3assets[3]['issueqty']),
    corp3ETH = str(corp3assets[4]['issueqty']),

    corp4GBP = str(corp4assets[0]['issueqty']),
    corp4USD = str(corp4assets[1]['issueqty']),
    corp4CAD = str(corp4assets[2]['issueqty']),
    corp4BTC = str(corp4assets[3]['issueqty']),
    corp4ETH = str(corp4assets[4]['issueqty']),

    corp5GBP = str(corp5assets[0]['issueqty']),
    corp5USD = str(corp5assets[1]['issueqty']),
    corp5CAD = str(corp5assets[2]['issueqty']),
    corp5BTC = str(corp5assets[3]['issueqty']),
    corp5ETH = str(corp5assets[4]['issueqty']),

    corp6GBP = str(corp6assets[0]['issueqty']),
    corp6USD = str(corp6assets[1]['issueqty']),
    corp6CAD = str(corp6assets[2]['issueqty']),
    corp6BTC = str(corp6assets[3]['issueqty']),
    corp6ETH = str(corp6assets[4]['issueqty']),

    corp7GBP = str(corp7assets[0]['issueqty']),
    corp7USD = str(corp7assets[1]['issueqty']),
    corp7CAD = str(corp7assets[2]['issueqty']),
    corp7BTC = str(corp7assets[3]['issueqty']),
    corp7ETH = str(corp7assets[4]['issueqty']),

    corp8GBP = str(corp8assets[0]['issueqty']),
    corp8USD = str(corp8assets[1]['issueqty']),
    corp8CAD = str(corp8assets[2]['issueqty']),
    corp8BTC = str(corp8assets[3]['issueqty']),
    corp8ETH = str(corp8assets[4]['issueqty']),

    corp9GBP = str(corp9assets[0]['issueqty']),
    corp9USD = str(corp9assets[1]['issueqty']),
    corp9CAD = str(corp9assets[2]['issueqty']),
    corp9BTC = str(corp9assets[3]['issueqty']),
    corp9ETH = str(corp9assets[4]['issueqty']),
    )

@app.route("/transact", methods=['POST'])
def echo(): 
    return "Transaction added to chain stream(s)"

